### ISSUE TITLE
Design Error in Services Section 

### ISSUE THREAD

**Issue by pranay202** [InfuriousICC/Bots-Encyclopedia#2]
#### bug
The services posted and the footer section is in a column-wise manner.

- Screenshots:
![image](https://user-images.githubusercontent.com/68046838/177305244-cdbfbe14-9da9-4456-916b-3458dd4f49ed.png)

- Changes required in: https://github.com/InfuriousICC/Bots-Encyclopedia/blob/main/services.html

#### Expected behavior
The services posted and the footer section is expected to be in a row-wise manner.

**Comment by pranay202** [comment]
I would like to work on this. Please assign it to me.

**Comment by dheerajydv19** [comment]
Thanks, Pranay for showing your interest in working with you. Please once contact me on any of my social media so that we can discuss this project and proceed further. We are extremely sorry for so late reply.
https://linktr.ee/dheerajydv19
